### PR TITLE
Fix setting versioned endpoints to `GraphiQLHandlerOptions`

### LINKED ISSUE #1538: GraphiQL URLs broken
Due to the added versioning in 0.8.0. Also check swagger URLs.

### PR DESCRIPTION
**Pull request by ferenc-csaky**
Fixes #1538

### CODE REVIEW

File: sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/ServerConfigUtil.java [hunk 1]
```diff
@@ -57,4 +59,41 @@ public static ServerConfig mergeConfigs(
...
+  /**
+   * Creates a copy of GraphiQL handler options with versioned URIs.
+   *
+   * @param version the version prefix to prepend to endpoints
+   * @param graphiQLHandlerOptions the original options to copy and version
+   * @return a new GraphiQL handler options instance with versioned endpoints, or null if input is
+   *     null
+   */
+  @Nullable
+  public static GraphiQLHandlerOptions createVersionedGraphiQLHandlerOptions(
```
Comment (mbroecheler) [inline sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/ServerConfigUtil.java:72]: Do we need to do something similar with Swagger?

Comment (ferenc-csaky) [reply sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/ServerConfigUtil.java:72]: nope, the `SwaggerConfig` class is completely our own POJO, so we do not need to hack around built-in vertx things.
