### PR TITLE
fix: Defined operations are ignored if GraphQL schema is inferred

### LINKED ISSUE #2021: Defined operations are ignored if GraphQL schema is inferred
When no explicit GraphQL schema is provided and the schema is inferred, any user-defined operation files are silently ignored and dropped from the compiled output.

### PR DESCRIPTION
**Pull request by mateczagany**
Fixes #2021 

- Preserve user-defined operations when GraphQL schema is inferred by adding a new, `defaultOperations` field
- Add unit tests

### CODE REVIEW

File: sqrl-planner/src/test/java/com/datasqrl/config/GraphqlSourceLoaderTest.java [hunk 1]
```diff
@@ -0,0 +1,246 @@
...
+        .isInstanceOf(IllegalArgumentException.class)
+        .hasMessageContaining("does-not-exist.graphql");
+  }
+
+  private static ScriptFiles scriptFiles(
+      @Nullable String graphql, List<String> operations, List<ScriptApiConfig> apiConfigs) {
+    return new ScriptFiles(stubPackageJson(graphql, operations, apiConfigs));
+  }
+
+  private static PackageJson stubPackageJson(
```
Comment (ferenc-csaky) [inline sqrl-planner/src/test/java/com/datasqrl/config/GraphqlSourceLoaderTest.java]: Let's use mockito instead of defining these.

**Review by ferenc-csaky — COMMENTED** [review]
We had an offline discussion to shape `GraphqlSourceLoader` a bit to make its flow cleaner. Will check after that update.

**Review by ferenc-csaky — APPROVED** [review]
LGTM
